services:
  # This service is the base Isaac Lab image
  isaac-lab:
    env_file:
      - .env.base
    build:
      args:
        - ISAACSIM_VERSION_ARG=${ISAACSIM_VERSION}
        - ISAACSIM_ROOT_PATH_ARG=${DOCKER_ISAACSIM_ROOT_PATH}
        - ISAACLAB_PATH_ARG=${DOCKER_ISAACLAB_PATH}
        - DOCKER_USER_HOME_ARG=${DOCKER_USER_HOME}
    environment:
      - ISAACSIM_PATH=${DOCKER_ISAACLAB_PATH}/_isaac_sim
      - OMNI_KIT_ALLOW_ROOT=1
      - ISAACSIM_ROOT_PATH=${DOCKER_ISAACSIM_ROOT_PATH}
      - ISAACLAB_PATH=${DOCKER_ISAACLAB_PATH}