services:
  # This service is the base Isaac Lab image
  isaac-lab:
    build:
      target: ${TARGET}
      context: ../
      dockerfile: docker/Dockerfile
    image: isaac-lab-${TARGET}
    container_name: isaac-lab-${TARGET}
    environment:
      - OMNI_KIT_ALLOW_ROOT=1
      - ACCEPT_EULA=Y
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    # This is the entrypoint for the container
    entrypoint: bash
    stdin_open: true
    tty: true