# Copyright (c) 2024 Boston Dynamics AI Institute LLC. All rights reserved.
# This section defines the build system requirements
[build-system]
requires = ["setuptools", "toml"]
build-backend = "setuptools.build_meta"
