# IsaacLab volumes
# Optionally injected at runtime to allow extension architecture to share them
services:
  isaac-lab:
    volumes:
        # This overlay allows changes on the local files to
        # be reflected within the container immediately
      - type: bind
        source: ../../source
        target: ${DOCKER_ISAACLAB_PATH}/source
      - type: bind
        source: ../../docs
        target: ${DOCKER_ISAACLAB_PATH}/docs
        # The effect of these volumes is twofold:
        # 1. Prevent root-owned files from flooding the _build and logs dir
        #    on the host machine
        # 2. Preserve the artifacts in persistent volumes for later copying
        #    to the host machine
      - type: volume
        source: isaac-lab-docs
        target: ${DOCKER_ISAACLAB_PATH}/docs/_build
      - type: volume
        source: isaac-lab-logs
        target: ${DOCKER_ISAACLAB_PATH}/logs
      - type: volume
        source: isaac-lab-data
        target: ${DOCKER_ISAACLAB_PATH}/data_storage

volumes:
  # isaac-lab
  isaac-lab-docs:
  isaac-lab-logs:
  isaac-lab-data:
