# Extension of base.yaml to support the 'ros2' stage of the Dockerfile
services:
  isaac-lab:
    extends:
      file: base.yaml
      service: isaac-lab
    build:
      args:
      # Set the version of the ROS2 apt package to install (ros-base, desktop, desktop-full)
      - ROS2_APT_PACKAGE=ros-base
    environment:
      # Set ROS2 middleware implementation to use (e.g. rmw_fastrtps_cpp, rmw_cyclonedds_cpp)
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      # Path to fastdds.xml file to use (only needed when using fastdds)
      - FASTRTPS_DEFAULT_PROFILES_FILE=${DOCKER_USER_HOME}/.ros/fastdds.xml
      # Path to cyclonedds.xml file to use (only needed when using cyclonedds)
      - CYCLONEDDS_URI=${DOCKER_USER_HOME}/.ros/cyclonedds.xml